language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt

before_script:
  - pip install coala-bears

script:
  - coala --non-interactive -V

after_success:
  - ./.ci/build.sh
