# Generated by Django 2.0.4 on 2018-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
