# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, null=True)),
                ('url', models.URLField(null=True)),
                ('summary', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('year_of_release', models.CharField(max_length=100, null=True)),
                ('genre', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('actors_and_directors', models.TextField(null=True)),
                ('votes_and_gross', models.TextField(null=True)),
                ('other_info', models.TextField(null=True)),
            ],
        ),
    ]
